// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCn3e2WpVttJ2dXEZNWX4yUNs1PZIIoR4',
    appId: '1:134366064831:web:cfb1a67bea7633440cd60a',
    messagingSenderId: '134366064831',
    projectId: 'smarttear-app',
    authDomain: 'smarttear-app.firebaseapp.com',
    storageBucket: 'smarttear-app.firebasestorage.app',
    measurementId: 'G-4TV4ZDJCD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhLCKeWSMWKn4C9QMSJMqeGcHvOrIog4s',
    appId: '1:134366064831:android:5b5fb7863a9da3df0cd60a',
    messagingSenderId: '134366064831',
    projectId: 'smarttear-app',
    storageBucket: 'smarttear-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnkWq03TfkyIiC-2ov0wNBkYU8fjPx1Vo',
    appId: '1:134366064831:ios:0538fa16deccb2980cd60a',
    messagingSenderId: '134366064831',
    projectId: 'smarttear-app',
    storageBucket: 'smarttear-app.firebasestorage.app',
    iosClientId: '134366064831-403outu70kddkbsguum62o4fjtoj72m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarttear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnkWq03TfkyIiC-2ov0wNBkYU8fjPx1Vo',
    appId: '1:134366064831:ios:0538fa16deccb2980cd60a',
    messagingSenderId: '134366064831',
    projectId: 'smarttear-app',
    storageBucket: 'smarttear-app.firebasestorage.app',
    iosClientId: '134366064831-403outu70kddkbsguum62o4fjtoj72m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarttear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCn3e2WpVttJ2dXEZNWX4yUNs1PZIIoR4',
    appId: '1:134366064831:web:9fc9c6c54cb5c6b40cd60a',
    messagingSenderId: '134366064831',
    projectId: 'smarttear-app',
    authDomain: 'smarttear-app.firebaseapp.com',
    storageBucket: 'smarttear-app.firebasestorage.app',
    measurementId: 'G-GKQBZTBBVD',
  );
}
